### PR TITLE
Remove Rails from namespace

### LINKED ISSUE #16: Accessing Rails.env in a model results in an error
### Describe the bug

I can't use Rails.env (e.g. Rails.env.test?) anymore in Models, resulting in:

```
     Failure/Error: return if Rails.env.test?

     NoMethodError:
       undefined method `env' for module Aws::Record::Rails
     # ./app/models/user.rb:121:in `email_is_unique'
     # ./spec/models/user_spec.rb:30:in `block (3 levels) in <top (required)>'
```

Only when I use `::Rails.env.test?` it works.

### Expected Behavior

Rails.env should have the expected behavior

### Current Behavior

Rails.env is not available, only ::Rails.env

### Reproduction Steps

Access Rails.env in any model.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-record-rails latest

### Environment details (Version of Ruby, OS environment)

Ruby 3.3.6 macos

### PR DESCRIPTION
**Pull request by mullermp**
Fixes #16

Removes the `Rails` namespace and places VERSION on the Railtie instead. Everything is still loaded and `Rails` is assumed to be the root namespace.

### CODE REVIEW

**Review by jterapin — APPROVED** [review]

File: lib/aws-record-rails.rb [hunk 1]
```diff
@@ -14,14 +14,12 @@
 
 module Aws
   module Record
-    module Rails
+    # Rails tasks for Aws::Record
+    class Railtie < ::Rails::Railtie
```
Comment (jterapin) [inline lib/aws-record-rails.rb:18]: Should the file name be changed to match the namespace?

Comment (jterapin) [reply lib/aws-record-rails.rb:18]: Disregard - just realized the gem name, heh.

Comment (mullermp) [reply lib/aws-record-rails.rb:18]: No it should be the gem name here, but yeah I think "best practice" would be a railtie file.
